Models/NavigationLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestInternet_umbraco.Models
{
    public class NavigationLink
    {
        public string Text { get; set; }
        public string Url { get; set; }
        public bool NewWindow { get; set; }
        public string Target { get { return NewWindow ? "_blank" : null; } }
        public string Title { get; set; }

        public NavigationLink()
        { }

        public NavigationLink(string url, string text = null, bool newWindow = false, string title = null)
        {
            Text = text;
            Url = url;
            NewWindow = newWindow;
            Title = title;
        }
    }
}

Models/NavigationListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections.Generic;
using System.Linq;

namespace BestInternet_umbraco.Models
{
    public class NavigationListItem
    {
        public string Text { get; set; }
        public NavigationLink Link { get; set; }
        public List<NavigationListItem> Items { get; set; }
        public bool HasChildren { get { return Items != null && Items.Any() && Items.Count > 0; } }

        public NavigationListItem()
        { }

        public NavigationListItem(NavigationLink link)
        {
            Link = link;
        }

        public NavigationListItem(string text)
        {
            Text = text;
        }
    }
}

Models/providerPackages.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestInternet_umbraco.Models
{
    public class providerPackages
    {
        public string provider { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;


namespace BestInternet_umbraco.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Home/";
        public ActionResult RenderHeader()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Header.cshtml");
        }

        public ActionResult RenderFnos()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Fnos.cshtml");
        }

        public ActionResult RenderDeals()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Deals.cshtml");
        }

        public ActionResult RenderCta()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Cta.cshtml");
        }

        public ActionResult RenderCompare()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Compare.cshtml");
        }

        public ActionResult RenderCoverageMap()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_CoverageMap.cshtml");
        }

        public ActionResult RenderProviders()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Providers.cshtml");
        }
    }
}

Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Web.Mvc;
using System.Web.Mvc;
using BestInternet_umbraco.Models;
using Umbraco.Core.Models;
using System.Runtime.Caching;
using Umbraco.Web;
using Umbraco.Core.Models.PublishedContent;

namespace BestInternet_umbraco.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";
      

        public ActionResult RenderFooter()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Footer.cshtml");
        }


        /// <summary>
        /// Renders the top navigation in the nevheader partial
        /// </summary>
        /// <returns>Partial view with a model</returns>
        public ActionResult RenderNavHeader()
        {
            //return PartialView(PARTIAL_VIEW_FOLDER + "_NavHeader.cshtml");
            
            //List<NavigationListItem> nav = GetNavigationModelFromDatabase();

            List<NavigationListItem> nav = GetObjectFromCache<List<NavigationListItem>>("mainNav", 5, GetNavigationModelFromDatabase);
            return PartialView(PARTIAL_VIEW_FOLDER + "_NavHeader.cshtml", nav);
        }
 
      

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible");
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        /// <summary>
        /// A generic function for getting and setting objects to the memory cache.
        /// </summary>
        /// <typeparam name="T">The type of the object to be returned.</typeparam>
        /// <param name="cacheItemName">The name to be used when storing this object in the cache.</param>
        /// <param name="cacheTimeInMinutes">How long to cache this object for.</param>
        /// <param name="objectSettingFunction">A parameterless function to call if the object isn't in the cache and you need to set it.</param>
        /// <returns>An object of the type you asked for</returns>
        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];
            if (cachedObject == null)
            {
                CacheItemPolicy policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }
            return cachedObject;
        }
    }
}

Views/Carousel.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Carousel>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Web.cshtml";

        PackagesListing packages = new PackagesListing(Umbraco.TypedContent(1143));

        //List<IPublishedContent> filteredPackages = packages.Children(x => x.GetPropertyValue<IEnumerable<IPublishedContent>>("fno").FirstOrDefault().Id == Model.Content.Id).ToList();
          List<IPublishedContent> chosenPackage = packages.Children(x => x.Id == Model.Content.BannerDeal.FirstOrDefault().Id).ToList();
    
          List<IPublishedContent> bestDeal = packages.Children(x => x.Id == Model.Content.BestValueDeal.FirstOrDefault().Id).ToList(); 
          List<IPublishedContent> deal1 = packages.Children(x => x.Id == Model.Content.HomePageDeal1.FirstOrDefault().Id).ToList(); 
          List<IPublishedContent> deal2 = packages.Children(x => x.Id == Model.Content.HomePageDeal2.FirstOrDefault().Id).ToList(); 

       
          var packageMainImage = String.Empty;    
                        var packageImage = Umbraco.TypedMedia(Model.Content.GetPropertyValue<int>("backgroundImage"));
                        if (packageImage != null)
                        {
                            packageMainImage = packageImage.Url;
                        }

}

@*@{ Html.RenderAction("RenderHeader", "Home");}*@

    <div class="cookie-banner">
        <p class="covid-alert"><img class="popup-logo" src="covid/health-logo.jpg" alt="South Africa Health Department Logo">For news and information regarding <strong>COVID-19</strong> please visit <a class="covid-sa" href="http://www.sacoronavirus.co.za" target="_blank">SA Corona Virus</a></p>
        <button class="close">&times;</button>
    </div>

    <div class="header-banner" style="background-image:url(@Model.Content.BackgroundImage.Url)">
        <div class="header-content-wrapper">
            <div class="header-content-box">


                @foreach (ProviderPackages package in chosenPackage)
                {
                    <h1>@package.Type.FirstOrDefault().Name.ToUpper()</h1>
                    <div class="white-bold">@package.Speed Mbps Speed</div>
                    <p class="white">Get the best internet money can buy. With Best Internet we help you get more than what you bargained for.</p>
                    <div class="header-price-wrapper">
                        <p class="per-month">From: </p>
                        <div class="price">@package.Price</div>
                        <p class="per-month">/per month</p>
                    </div>
                    <div class="header-btn-wrapper">
                        <a href="@package.Url" class="header-btn-green w-button">APPLY NOW</a>
                        <a href="#coverage-map" class="header-btn-stroke w-button">CHECK COVERAGE</a>
                    </div>
                }


            </div>
        </div>
    </div>


@{ Html.RenderAction("RenderFnos", "Home");}


<div id="introduction" class="introduction-section">


    <div class="content-container">
        <div class="sub-heading-content">WE PICKED OUT THE BEST PACKAGES.</div>
        <h2>LET'S GET YOU STARTED</h2>
        <p class="centre">See what deals your favourite providers have for you. Don’t forget to check your coverage to make sure<br>these packages work in your area!</p>
        <div class="div-block">


            @foreach (ProviderPackages package in Model.Content.HomePageDeals)
            {
                bool isLte = package.Type.FirstOrDefault().Name == "LTE";
               
       
                <div class="card-container">
                    <div class="card-header-box">@Html.Raw(isLte ? "" : "<img src="+@package.FnoSmallLogo.Url+" width='70'>")  </div><img src="@package.ProviderSmallLogo.Url" height="40" alt="" class="fno-logo-card">
                      <div class="card-speed-sub">@(isLte ? package.Data + "GB LTE" : package.Speed + "Mbps Fibre")</div>
                    <div class="card-speed-wrapper">
                        <div class="card-speed-container">
                            <img src="@(isLte ? "images/day-icon.svg" : "images/arrow-up.svg")" width="30" alt="" class="arrow-speed">
                            <div class="card-speed-upload">@(isLte ? package.DayData + "GB"  : package.Upload + "Mbps")</div>
                            <div class="speed-sub">@(isLte ? "Day" : "Upload")</div>
                        </div>
                        <div class="card-speed-container">
                            <img src="@(isLte ? "images/night-icon.svg" : "images/arrow-down.svg")" width="30" alt="" class="arrow-speed">
                            <div class="card-speed-upload">@(isLte ? package.NightData + "GB" : package.Download + "Mbps")</div>
                            <div class="speed-sub">@(isLte ? "Night" : "Download")</div>
                        </div>
                    </div>
                    <div class="card-price">@package.Price/pm</div><a href="@package.Url" class="card-btn w-button">APPLY NOW</a>
                    @Html.Raw(Model.Content.HomePageDeals.FirstOrDefault().Id == package.Id ? "<img src='images/best-value-ribbon.svg' width='131' alt='' class='ribbon-tag'>" : "")
                </div>
            }

          
        </div>
    </div>
</div>


@{ Html.RenderAction("RenderCta", "Home");}
@{ Html.RenderAction("RenderCompare", "Home");}
@{ Html.RenderAction("RenderCoverageMap", "Home");}
@{ Html.RenderAction("RenderProviders", "Home");}

Views/Meta.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Meta>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Views/MetaTags.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MetaTags>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Views/PackageListing.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.PackagesListing>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Web.cshtml";

    List<IPublishedContent> packageItems = Model.Content.Children().ToList();


}

@foreach (ProviderPackages package in packageItems)
{

    <h2>@package.Name</h2>
    if (package.HasValue("fNO"))
    {
        FNos fno = new FNos(package.FNO.FirstOrDefault());
        @fno.BannerHeader
        <p>FNO: @fno.Name</p>
        
    }

}

Views/PackageSettings.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.PackageSettings>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Views/Partials/ContentBlocks/Carousel.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Carousel>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    IPublishedContent currentPageNode = (IPublishedContent)ViewData["currentPageNode"];
    Carousel carousel = new Carousel(Model.Content);
    var count = 0;
    var active = (count == 0 ? "active" : "");
}
@if (carousel.HasValue("carouselSlides"))
{
    IEnumerable<IPublishedContent> collection = carousel.Slides.ToContentSet();
    bool display = collection.Count() > 1 ? true : false;

    var row = ViewData["row"];


                <div>
                    <div class="carouselholder">
                   
                        @{
                            Html.RenderPartial("~/Views/Partials/NestedMaster.cshtml", Model.Content, new ViewDataDictionary { { "currentPageNode", currentPageNode }, { "collection", collection } });
                        }
                    </div>
                </div>
            }

Views/Partials/ContentBlocks/CarouselSlide.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.CarouselSlide>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    IPublishedContent currentPageNode = (IPublishedContent)ViewData["currentPageNode"];
    CarouselSlide carouselslide = new CarouselSlide(Model.Content);
    ProviderPackages package = new ProviderPackages(carouselslide.BannerDeal);
    var count = 0;
    var active = (count == 0 ? "active" : "");
}
<div class="header-banner" style="background-image:url(@carouselslide.BackgroundImage.Url)">
    <div class="header-content-wrapper">
        <div class="header-content-box">

            <h1>@package.Type.FirstOrDefault().Name.ToUpper() FIBRE</h1>
            <div class="white-bold">@package.Speed Mbps Speed</div>
            <p class="white">Get the best internet money can buy. With Best Internet we help you get more than what you bargained for.</p>
            <div class="header-price-wrapper">
                <p class="per-month">From: </p>
                <div class="price">@package.Price</div>
                <p class="per-month">/per month</p>
            </div>
            <div class="header-btn-wrapper">
                <a href="@package.Url" class="header-btn-green w-button">GET THIS DEAL</a>
                <a href="#coverage-map" class="header-btn-stroke w-button">CHECK COVERAGE</a>
            </div>

        </div>
    </div>
</div>

Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Views/Web.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
  

@{
	Layout = null;

    
}

@* the fun starts here *@

<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Mon Feb 24 2020 11:45:52 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5e3aa9df3b4cb91f095d7dae" data-wf-site="5e3aa9df3b4cb96fca5d7dad" lang="en">
<head>

    @Html.Partial("/Views/Partials/meta.cshtml")

    @*<meta charset="utf-8">
        <title>Best Internet | Fibre &amp; LTE Comparison</title>
        <meta content="Best Internet brings you the best comparative internet deals in South Africa. Choose from and compare internet service providers and packages at your fingertips!" name="description">
        <meta content="Best Internet | Fibre &amp; LTE Comparison" property="og:title">
        <meta content="Best Internet brings you the best comparative internet deals in South Africa. Choose from and compare internet service providers and packages at your fingertips!" property="og:description">
        <meta content="summary" name="twitter:card">
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <meta content="Webflow" name="generator">*@
    <link href="/css/normalize.css" rel="stylesheet" type="text/css">
    <link href="/css/webflow.css" rel="stylesheet" type="text/css">
    <link href="/css/best-internet-v2.webflow.css" rel="stylesheet" type="text/css">
    @*<link href="/css/style.css" rel="stylesheet" type="text/css">*@
    @RenderSection("styles", false);
    <link href="/covid/pop-style.css" rel="stylesheet">
    <script src="https://use.typekit.net/nvx1mzb.js" type="text/javascript"></script>
    <script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>

    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-M78CZ88');</script>
    <!-- End Google Tag Manager -->

    <script type="text/javascript">
        /** This section is only needed once per page if manually copying **/
        if (typeof MauticSDKLoaded == 'undefined') {
            var MauticSDKLoaded = true;
            var head = document.getElementsByTagName('head')[0];
            var script = document.createElement('script');
            script.type = 'text/javascript';
            script.src = 'https://campaign.igdigital.co.za/index.php/media/js/mautic-form.js';
            script.onload = function () {
                MauticSDK.onLoad();
            };
            head.appendChild(script);
            var MauticDomain = 'https://campaign.igdigital.co.za/index.php';
            var MauticLang = {
                'submittingMessage': "Please wait..."
            }
        }
    </script>

    <script>

        var lading_url = "";
        function setCookie(cname, cvalue, exdays) {
            var d = new Date();
            d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
            var expires = "expires=" + d.toGMTString();
            document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
        }

        function getCookie(cname) {
            var name = cname + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
            var ca = decodedCookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }

        function checkCookie() {
            var url = getCookie("page_url");
            if (url == "") {
                setCookie("page_url", window.location.href, 30);
            } else if (url == null) {
                setCookie("page_url", window.location.href, 30);
            }
        }
    </script>

    @RenderSection("Head", false)

</head>
<body onload="checkCookie()">
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M78CZ88"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    @RenderSection("ScriptsTop", false)

    @*@{ Html.RenderAction("RenderNavHeader", "SiteLayout");}*@


    <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar-container w-nav">
        <div class="container w-container">
            <a href="/" class="brand w-nav-brand w--current"><img src="/images/best-internet-logo.svg" width="186" alt="" class="logo"></a>
            <nav role="navigation" class="nav-menu w-nav-menu">


                @* @RenderChildItems(Model)*@

                @Html.CachedPartial("~/Views/Partials/SiteLayout/MenuNavigation.cshtml", Model.Content, 3600, true)

                @*<a href="/" class="nav-link w-nav-link w--current">HOME</a>
                    <a href="/providers" class="nav-link w-nav-link">PROVIDERS</a>
                    <a href="/blog/" class="nav-link w-nav-link">BLOG</a>
                    <a href="/contact-us/" class="nav-link w-nav-link">CONTACT US</a>*@

            </nav>
            <div class="menu-button w-nav-button">
                <div class="icon w-icon-nav-menu"></div>
            </div>
        </div>
    </div>

    @RenderBody()


    @Html.CachedPartial("~/Views/Partials/SiteLayout/_Footer.cshtml", Model.Content, 3600, false)
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    @RenderSection("ScriptsBottom", false)
    <script src="/js/webflow.js" type="text/javascript"></script>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $('.close').click(function (e) {
            $('.cookie-banner').fadeOut();
        });
    </script>
    <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
    <script src="~/Scripts/isotope.pkgd.min.js"></script>


    <script>
        // external js: isotope.pkgd.js

        // init Isotope
        var $grid = $('.package-grid').isotope({
            itemSelector: '.grid-item'
        });

        // store filter for each group
        var filters = {};

        $('.filters').on('change', function (event) {
            var $select = $(event.target);
            // get group key
            var filterGroup = $select.attr('value-group');
            // set filter for group
            filters[filterGroup] = event.target.value;
            // combine filters
            var filterValue = concatValues(filters);
            // set filter for Isotope
            $grid.isotope({ filter: filterValue });
        });

        // flatten object by concatting values
        function concatValues(obj) {
            var value = '';
            for (var prop in obj) {
                value += obj[prop];
            }
            return value;
        }

    </script>




</body>
</html>